Repository openshift-knative/knative-openshift-ingress, pull requests merged in 2019-11, with the labels that each got.

#24 Change Route name to unique
  pkg/controller/common/reconciler.go
  pkg/controller/ingress/ingress_controller_test.go
  pkg/controller/resources/route.go
  pkg/controller/resources/route_test.go
Labels: size/L

#26 Actually return the reconciler error if it happens.
  pkg/controller/clusteringress/clusteringress_controller.go
  pkg/controller/common/reconciler.go
  pkg/controller/ingress/ingress_controller.go
Labels: size/S

#27 Only reconcile Istio ingress into the SMMR
  pkg/controller/clusteringress/clusteringress_controller_test.go
  pkg/controller/common/reconciler.go
  pkg/controller/ingress/ingress_controller_test.go
Labels: lgtm, size/L

#28 [SRVKS-337] Use hash based route name suffix rather than an index.
  pkg/controller/clusteringress/clusteringress_controller_test.go
  pkg/controller/ingress/ingress_controller_test.go
  pkg/controller/resources/route.go
  pkg/controller/resources/route_test.go
Labels: size/S

#30 fix issue for cluster local service
  pkg/controller/common/reconciler.go
  pkg/controller/ingress/ingress_controller_test.go
Labels: lgtm, size/M

#29 Remove namespace information from SMMR if that namespace contains empty ingress object
  pkg/controller/clusteringress/clusteringress_controller.go
  pkg/controller/common/reconciler.go
  pkg/controller/ingress/ingress_controller.go
  pkg/controller/ingress/ingress_controller_test.go
Labels: lgtm, size/L

#31 Install a default allow-all NetworkPolicy
  pkg/controller/common/reconciler.go
  pkg/controller/ingress/ingress_controller_test.go
  pkg/controller/resources/network_policy.go
Labels: lgtm, size/L

#35 Remove obsolete routes in other namespaces even if the names match.
  pkg/controller/common/reconciler.go
  pkg/controller/ingress/ingress_controller_test.go
Labels: size/S

#36 [SRVKS-325] Add TLS route with edge termination
  pkg/controller/ingress/ingress_controller_test.go
  pkg/controller/resources/route.go
  pkg/controller/resources/route_test.go
Labels: lgtm, size/L
